language: node_js
node_js:
- 10
- 11
- 12
jobs:
  include:
  - if: type = pull_request
    node_js: 12
    stage: expect_version_bump
    script: yarn check-for-version-bump
  - node_js: 12
    if: branch = master
    stage: deploy
    deploy:
      api_key:
        secure: D0Uj3iIA8W+GjwtC0ixO8wZ8g2k2/oEASJkY/C3x/rs0ssMTvqvEQfUqbmjGaDeIXeaeSOczOez62ycw1gyHv6mk5CAHdt2lZ8V0y81AOuKHhrEOutkRXz4bgWXdamm/paH+JWRO/FVcozrE2tYi7sU7kkkz6A667NuXekGv4sWJItb5/hQv6akE894LgH1cvMw4erqy8xG9muobITpE3X2In3mMl7Vb8R1hHoCezILx4zXy9otvxvZEig8rU/zysyFHSJq9xoxHBq2oKweTYgS9gwNOETHVO1gpmR35/cwEnsmNBAtgc3KWUHqfCRQvqBxcxdj5kKcJjKs9Dhp8rWUoq+zhQxwo2IP6zAyQcgXzcFj00XM1jIdAyxYpPWE1/+xNyLVNrfElFrsLIxAX6Hxm2Ro5a2U1uckE2JwZzKdMnPfat0kfi2bd97mPBkl7K0dKgTMMikIXAGA3lIKTHEQYQeAcaglfPk6aOPuqv/CCqyRYWEIftC+TlyZM2q4Fwl4mkUNoJvL9xgt18oghBd8joSn6jfoSTJs/wF5f/A0URO1kHiK0ZRsS2sQ1SbQVeureRXggpybkaQRCLrQ0LGPie1DhvibculAVfJpXEDNUH9+Y9DUvozd5bQ4fuQR76uZj8q8FfbUgirZlwXtfk9PjIIYdUodap8dz3efDJ7M=
      email: npm@0ti.me
      provider: npm
      skip_cleanup: true
      on:
        branch: master
        repo: 0time/index-generator
