language: node_js
node_js:
- 10
- 11
- 12
jobs:
  include:
  - if: type = pull_request
    node_js: 12
    stage: expect_version_bump
    script: yarn check-for-version-bump
  - node_js: 12
    if: branch = master
    stage: deploy
    deploy:
      api_key:
        secure: "JjKAqc81DKAPa5SRezK7H3NcyVsc/LkTVLayYwyU/u0BJQQw/T/GqhourwhiaRLjQWUp/3wrIPbONJp+8uLxBMAmLMXRL+p83zjpsyxYvr4dvLXzOSIqGf3FuJIomAM5y6GPPslr/iTLuG4xcBngODxVnQJ8Xbw5GY0XcO2lkH9/Zbb6bEvuy2MKHExHla3L0uSNtmzL9KfKhsc1kOxdY51SlrF0xpul4ER7JFfAj3HUKZit7gUvCDyYqLHzTXopJY2yyVhOwK86MBSeXeqtGhqEdm4QXQD9yQFlPSgNUiM166syrlF7njl0qFaOf1QySTluXyuJqFlVAhD//YPqCK32dN3pmJw0WZvmDQ1i0vYPsLkmLjvQ7+TaDH9rcSsdV3oz4k7NJ0wKQ7qmjAJqAeIn9+Pv7Ud0bjvLCSvNNLpY+rtbwGmN5pBbileeaaSOIZ7bKSeUJ/UU2iswAfLA5YQjWXTKKxckgXKoUnc6wv8aAZcLtixev0HP4PMqi12tcVygwxLRQ3SVQdE8YcqR0OQKHaucmErgwv7FUooJ/KO8c1oFdkyudk2vk0eP/Y9kKmCSaktLrKaijvvWxUeZWG9fkFdppbzcoTrnPn6KEHnBWb3TtPd+nipj+LTwacdvSVhtuuzEwPQmhfj2vwMhOzUxvGbtNoZUDwJDyZlOoHs="
      email: npm@0ti.me
      provider: npm
      on:
        branch: master
        repo: 0time/index-generator
